build_from:
  amd64: ghcr.io/home-assistant/amd64-base:latest
  aarch64: ghcr.io/home-assistant/aarch64-base:latest
  armv7: ghcr.io/home-assistant/armv7-base:latest
  armhf: ghcr.io/home-assistant/armhf-base:latest
  i386: ghcr.io/home-assistant/i386-base:latest
args:
  BUILD_VERSION: "5.13.62"
labels:
  org.opencontainers.image.title: "TF2 Trading Hub"
  org.opencontainers.image.version: "5.13.62"
  org.opencontainers.image.source: "https://github.com/DenyTwo918/TF2-HA"
